-- Run once in the BOW Supabase project's SQL Editor.
-- This table is intentionally separate from BOW workstream data.
create table if not exists public.staking_monitor_snapshots (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null,
  source_slot bigint not null unique,
  finalized_epoch bigint,
  consensus_balance_eth numeric(22,9) not null,
  execution_wallet_balance_eth numeric(22,9) not null default 0,
  eth_usd numeric(18,6),
  validator_snapshots jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists staking_monitor_snapshots_observed_at_idx
  on public.staking_monitor_snapshots (observed_at desc);

alter table public.staking_monitor_snapshots enable row level security;

-- No browser policies are created. The Staking Vercel function uses the
-- service-role key server-side, which bypasses RLS; clients only call that
-- function and never receive a Supabase credential.
